### ISSUE TITLE
package installation

### ISSUE THREAD

**Issue by AntoineSoetewey** [goepp/aspline#1]
Dear Vivien,
`devtools::install_github("monneret/bandsolve")` throws an error, so I cannot install `aspline`. Any idea how I could fix this?
Thanks in advance.
Best,
Antoine

<img width="1392" alt="Screenshot 2020-04-14 at 09 16 15" src="https://user-images.githubusercontent.com/17910063/79196646-bc3f0c80-7e30-11ea-96cd-9e827090c8c8.png">

**Comment by goepp** [comment]
Hi,
Sorry for late reply.
I could not reproduce your problem. Could you provide the output given by `devtools::install_github("monneret/bandsolve")`?
Best,
Vivien

**Comment by AntoineSoetewey** [comment]
Thanks for your reply. Here is the output:

<img width="1392" alt="Screenshot 2020-09-20 at 19 11 13" src="https://user-images.githubusercontent.com/17910063/93717275-0e6d2200-fb75-11ea-9152-f2412c68dd26.png">

Regards,
Antoine

**Comment by goepp** [comment]
I found a [similar issue](https://github.com/r-lib/devtools/issues/2033) where installation of a package which includes C/C++ code fails on Windows.
It is advised to [download Rtools](https://rstats.wtf/set-up-an-r-dev-environment.html#windows-system-prep). Could you try this, by following the latter link and the included installation instructions?

**Comment by AntoineSoetewey** [comment]
Thanks for your reply.

I am using a Mac, and I have installed Xcode from the Mac app store as advised in [this section](https://rstats.wtf/set-up-an-r-dev-environment.html#macos-system-prep). I still have the same issue, however.

**Comment by goepp** [comment]
Since I don't have a mac, I cannot try to reproduce the error.
I have found similar issues with macOS [here](https://github.com/r-lib/devtools/issues/1879) and [here](https://stackoverflow.com/questions/38725060/error-could-not-find-build-tools-necessary-to-build-stringi-when-trying-devto).
Can you try the checks mentioned there? In *particular*:
- using `devtools::install_github` from the command line, 
- updating the version of RStudio, or 
- disable RStudio's build tool detection code with `options(buildtools.check = function(action) TRUE)`.

EDIT: I corrected a bug that was preventing another user from installing `aspline`. @AntoineSoetewey, could you check if this fixes your issue?

**Comment by AntoineSoetewey** [comment]
Thanks for your message. I just tried, same issue...

**Comment by goepp** [comment]
After reading [this issue](https://github.com/rstudio/rstudio/issues/4175), the problem seems to be linked to how RStudio checks for tools for compiling R packages that include C code. As explained in that thread, the bug seems to be linked to a version of XCode and MacOS.

Have you tried [this fix](https://github.com/rstudio/rstudio/issues/4175#issuecomment-463502432)?
If it fails, could you give the output of `rstudioapi::buildToolsCheck()` run in RStudio and give your versions of XCode and MacOS?

**Comment by AntoineSoetewey** [comment]
Thanks for your message.

So I renamed `~/.R/Makevars` by `~/.R/old_Makevars`, as you can see to the right of the screenshot:

![Screenshot 2020-10-21 at 13 08 40](https://user-images.githubusercontent.com/17910063/96711879-8c079600-139e-11eb-84d2-0b6d1075b11c.png)

Output of `rstudioapi::buildToolsCheck()` is on the left of the above screenshot.

Moreover, version of MacOS is 10.15.7 (19H2) and version of Xcode is Version 12.1 (12A7403)

**Comment by goepp** [comment]
By bad, I forgot to mention to try `remotes::install_github('goepp/aspline')` and not `remotes::install_github('monneret/bandsolve')`.

However judging from the fact that `rstudioapi::buildToolsCheck()` returns `FALSE`, your problem looks to come from Xcode.

You could try to downgrade to Xcode 11.X (since this issue [seems to have appeared with Xcode 12.0](https://github.com/rstudio/rstudio/issues/4175#issuecomment-670942191)).

Another workaround is to try the by-hand installation explained [in the README](https://github.com/goepp/aspline#by-hand-installation), while running R not from within RStudio (as the bug looks to be due to Rstudio failing to detect Xcode tools), but from a terminal.

**Comment by goepp** [comment]
Since `aspline` can be installed on a MacOS machine running XCode 12.1 (see [here](https://github.com/goepp/aspline/pull/9/commits/7a2af15468846919223815f30fcbd28e23be8051)), I closed this issue.
